<?php

namespace ModelBundle\Repository;

/**
 * PeoplePhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeoplePhoneRepository extends \Doctrine\ORM\EntityRepository
{
}
