<?php

namespace ModelBundle\Repository;

/**
 * ShiptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiptoRepository extends \Doctrine\ORM\EntityRepository
{
}
